plataforma:
    resource: "@PlataformaBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation


principal:
    path: /
    defaults: { _controller: PlataformaBundle:Default:index }

login:
    path:     /login
    defaults: { _controller: PlataformaBundle:Usuario:login }

login_check:
    path: /login_check
logout:
    path: /logout

user_list:
    path: /direccion/listado_usuarios 
    defaults: { _controller: PlataformaBundle:Usuario:listuser }

user_registration:
    path:     /direccion/register
    defaults: { _controller: PlataformaBundle:Usuario:register }

cargar_persona:
    path:     /persona/register
    defaults: { _controller: PlataformaBundle:Persona:register }

cargar_alumno:
    path:     /alumno/register
    defaults: { _controller: PlataformaBundle:Alumno:register }

cargar:
    path:     /alumno/regis
    defaults: { _controller: PlataformaBundle:Alumno:alta }

