security:
# En el caso que los usuarios tengan la contraseña cifrada configuramos los encoders para la entidad en la que estén los usuarios
    encoders:

        PlataformaBundle\Entity\Usuarios:
                algorithm: bcrypt


# En providers le indicamos que los usuarios van a salir de la base de datos y el username será email
    providers:
            our_db_provider:
                        entity:
                            class: PlataformaBundle:Usuarios

    role_hierarchy:
            ROLE_ADMIN:       ROLE_USER
            ROLE_SUPER_ADMIN: ROLE_ADMIN

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            form_login:
                login_path: /login
                check_path: /login_check
            logout:
                path: /logout
                target: /


# Configuramos el firewall main para indicarle el provider, la login_path, login_check y el path del logout


    access_control:
                - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
                - { path: ^/direccion, roles: ROLE_SUPER_ADMIN }


