<?php

namespace PlataformaBundle\Repository;

/**
 * AlumnosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlumnosRepository extends \Doctrine\ORM\EntityRepository
{
}
