<?php

namespace PlataformaBundle\Repository;

/**
 * Config_cursoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Config_cursoRepository extends \Doctrine\ORM\EntityRepository
{
}
