<?php

namespace PlataformaBundle\Repository;

/**
 * InscripcionesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InscripcionesRepository extends \Doctrine\ORM\EntityRepository
{
}
