<?php

namespace PlataformaBundle\Repository;

/**
 * personasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class personasRepository extends \Doctrine\ORM\EntityRepository
{
}
