<?php

namespace PlataformaBundle\Repository;

/**
 * TutorAlumnosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TutorAlumnosRepository extends \Doctrine\ORM\EntityRepository
{
}
